version: "1.0"
services:
  worker:
    build: .
    environment:
      API_ID: $API_ID
      API_HASH: $API_HASH
      TOKEN: $TOKEN
      SUDO_USERS: $SUDO_USERS
      SESSION_NAME: $SESSION_NAME
      OWNER_USERNAME: $OWNER_USERNAME
      OWNER_ID: $OWNER_ID
